### ISSUE TITLE
Errors in parsKeys

### ISSUE THREAD

**Issue by AbderrSfa** [barimehdi77/ft_irc#14]
Some errors happen in parsKeys when no keys are given (args == 1). There is no args[1].
<img width="521" alt="Screen Shot 2022-05-01 at 1 52 16 PM" src="https://user-images.githubusercontent.com/58333462/166148980-7fb3340f-4db7-4b5a-b502-49505b0ef13c.png">

**Comment by barimehdi77** [comment]
this error is fixed I think! just test it again!
