### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by barimehdi77** [barimehdi77/ft_irc#4]
The last char in args[0] is always deleted.

<img width="797" alt="Screen Shot 2022-04-16 at 3 52 13 PM" src="https://user-images.githubusercontent.com/54292953/163682004-07fef0b0-ee31-4281-a8e3-ccbffb7ef2bd.png">

**Comment by AbderrSfa** [comment]
What??? That's new.
Okay I will check it.

**Comment by barimehdi77** [comment]
lmohim ana rah gha khdit dakshi li knti dayr o htito 3ndi

**Comment by AbderrSfa** [comment]
Fixed it. You were removing the last '\n' character. But my parsing was also removing it. So doing it twice makes the last char of the arg get deleted.

**Comment by barimehdi77** [comment]
so db hydtiha mn 3ndi wla mn 3ndk?

**Comment by AbderrSfa** [comment]
mn 3ndi
