### ISSUE TITLE
only one space between command and args

### ISSUE THREAD

**Issue by barimehdi77** [barimehdi77/ft_irc#8]
in parsing the all the params have to be separated with only one space

**DOC**: Internet Relay Chat: Server Protocol

<img width="982" alt="Screen Shot 2022-04-18 at 1 40 50 AM" src="https://user-images.githubusercontent.com/54292953/163741495-87e52b32-bd95-4410-adf8-fff3aee3a844.png">

<img width="854" alt="Screen Shot 2022-04-18 at 1 39 09 AM" src="https://user-images.githubusercontent.com/54292953/163741330-7b6be574-64aa-4511-a0dc-ebe767dc7908.png">

**Comment by AbderrSfa** [comment]
Fixed
