### ISSUE TITLE
User info seems to persist

### ISSUE THREAD

**Issue by AbderrSfa** [barimehdi77/ft_irc#9]
<img width="582" alt="Screen Shot 2022-04-21 at 2 41 22 PM" src="https://user-images.githubusercontent.com/58333462/164483941-eb178b80-21da-419e-8223-cb92d7a26764.png">
Register, quit then reconnect. The Info for the user doesn't get deleted.

**Comment by barimehdi77** [comment]
yes I know about this issue but I will fix it later

**Comment by barimehdi77** [comment]
The problem is: When there's only one Client and disconnect then reconnect the data stays, or when the lastest user connected disconnected then another user connected the server keeps it data with out deleted it
